---
- name: Install Instana agent
  hosts: all
  vars: 
    INSTANA_AGENT_KEY="please_add_my_agent_key"
    INSTANA_GPG_KEY="https://packages.instana.io/Instana.gpg"
    notify_hostname = "notify.test.local"
    notify_port = "8080"
    notify_server_username = "myusername"
    notify_server_password = "redhat123"
    notify_uri = "url/path/to/api"
  tasks:
  - name: Assert the system is red hat enterprise linux
    ansible.builtin.assert:
      that:
        - ansible_distribution == 'RedHat'
  
  - name: Copy the templates/instana-yum-repo.j2 to the /etc/yum.repos.d/ on the target hosts
    ansible.builtin.template:
      src: templates/instana-yum-repo.j2
      dest: /etc/yum.repos.d/Instana-Product.repo
    become: true

  - name: "Import the RPM gpg key from {{ INSTANA_GPG_KEY }}"
    ansible.builtin.rpm_key:
      key: "{{ INSTANA_GPG_KEY }}"
      state: present
    become: true
  
  - name: Install the rpm package instana-agent-static
    become: true
    ansible.builtin.package:
      name: instana-agent-static
      state: present
  
  - name: Install the rpm instana-agent-dynamic
    become: true
    ansible.builtin.package:
      name: instana-agent-dynamic
      state: present
  
  - name: Start the instana-agent service
    ansible.builtin.service:
      name: instana-agent
      state: started
      enabled: true
    become: true

  - name: Call an api with a json payload with a parameter of hostname
    ansible.builtin.uri:
      url: http://{{ notify_hostname }}:{{ notify_port }}/{{ notify_uri }}
      method: POST
      user: "{{ notify_server_username }}"
      password: "{{ notify_server_password }}"
      body:
        hostname: "{{ inventory_hostname }}"
      force_basic_auth: true
      status_code: 200
      body_format: json
      return_content: true
    register: api_result
  
  
  
